# Generated by Django 4.2 on 2023-04-18 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
