# Generated by Django 4.2 on 2023-04-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0024_alter_truck_truck_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='des_x',
        ),
        migrations.RemoveField(
            model_name='package',
            name='des_y',
        ),
        migrations.AlterField(
            model_name='package',
            name='addr_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='addr_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='wh_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
