# Generated by Django 4.2 on 2023-04-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0028_alter_package_addr_x_alter_package_addr_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='addr_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='addr_y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
