# Generated by Django 4.2 on 2023-04-21 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0008_alter_package_world_id_alter_truck_world_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='truck_id',
            field=models.ForeignKey(db_column='truck_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ups.truck'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='truck_id',
            field=models.AutoField(db_column='truck_id', primary_key=True, serialize=False),
        ),
    ]
