# Generated by Django 4.2 on 2023-04-20 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0007_alter_package_addr_x_alter_package_addr_y_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='world_id',
            field=models.ForeignKey(db_column='world_id', on_delete=django.db.models.deletion.CASCADE, to='ups.world'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='world_id',
            field=models.ForeignKey(blank=True, db_column='world_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='ups.world'),
        ),
        migrations.AlterField(
            model_name='world',
            name='world_id',
            field=models.AutoField(db_column='world_id', primary_key=True, serialize=False),
        ),
    ]
