version: '2'

services:
  db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      volumes:
            - data-volume:/var/lib/postgresql/data
  web-init:
      build: ./web-app
      command: /code/initserver.sh
      volumes:
        - ./web-app:/code
      depends_on:
        - db
  web:
      build: ./web-app
      user: nobody
      command: bash -c "/code/runserver.sh & python /code/send_email.py"
      volumes:
        - ./web-app:/code
      expose:
        - "8000"
      depends_on:
        - web-init
  nginx:
     image: nginx:latest
     ports:
       - "8000:8000"
     volumes:
       - ./nginx/config:/etc/nginx/conf.d
     depends_on:
       - web

  server:
    build: ./UPS
    user: root
    volumes:
      - ./UPS:/code
    command: bash -c "./run.sh"
    ports:
      - "12345:12345" # for world
      - "9999:9999" # for web
      - "5688:5688" # for ups
    expose:
      - "12345"
    depends_on:
      - web
volumes:
   data-volume:
