# Generated by Django 4.2 on 2023-04-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0009_alter_package_truck_id_alter_truck_truck_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='amazon_user_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
