# Generated by Django 4.2 on 2023-04-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0020_alter_package_wh_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='wh_id',
        ),
        migrations.AlterField(
            model_name='package',
            name='wh_id',
            field=models.IntegerField(),
        ),
    ]
