# Generated by Django 4.2 on 2023-04-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0021_remove_truck_wh_id_alter_package_wh_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='wh_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
