# Generated by Django 4.2 on 2023-04-25 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ups', '0025_remove_package_des_x_remove_package_des_y_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
