# Generated by Django 4.2 on 2023-04-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0026_alter_package_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
