# Generated by Django 4.2 on 2023-04-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0027_package_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='addr_x',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='addr_y',
            field=models.IntegerField(null=True),
        ),
    ]
